<!DOCTYPE html >
<html>
        <head>
          <title>exceptions - ScalaTest 3.0.2 - org.scalatest.exceptions</title>
          <meta name="description" content="exceptions - ScalaTest 3.0.2 - org.scalatest.exceptions" />
          <meta name="keywords" content="exceptions ScalaTest 3.0.2 org.scalatest.exceptions" />
          <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
          
      <link href="../../../lib/template.css" media="screen" type="text/css" rel="stylesheet" />
      <link href="../../../lib/diagrams.css" media="screen" type="text/css" rel="stylesheet" id="diagrams-css" />
      <script type="text/javascript" src="../../../lib/jquery.js" id="jquery-js"></script>
      <script type="text/javascript" src="../../../lib/jquery-ui.js"></script>
      <script type="text/javascript" src="../../../lib/template.js"></script>
      <script type="text/javascript" src="../../../lib/tools.tooltip.js"></script>
      
      <script type="text/javascript">
         if(top === self) {
            var url = '../../../index.html';
            var hash = 'org.scalatest.exceptions.package';
            var anchor = window.location.hash;
            var anchor_opt = '';
            if (anchor.length >= 1)
              anchor_opt = '@' + anchor.substring(1);
            window.location.href = url + '#' + hash + anchor_opt;
         }
   	  </script>
    


<!-- gtag [javascript] -->

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-71294502-1"></script>

<script defer>

window.dataLayer = window.dataLayer || [];

function gtag(){dataLayer.push(arguments);}

gtag('js', new Date());

gtag('config', 'UA-71294502-1');

</script>
        </head>
        <body class="value">

<!-- Top of doc.scalatest.org [javascript] -->

<script type="text/javascript">

var rnd = window.rnd || Math.floor(Math.random()*10e6);

var pid204546 = window.pid204546 || rnd;

var plc204546 = window.plc204546 || 0;

var abkw = window.abkw || '';

var absrc = 'http://ab167933.adbutler-ikon.com/adserve/;ID=167933;size=468x60;setID=204546;type=js;sw='+screen.width+';sh='+screen.height+';spr='+window.devicePixelRatio+';kw='+abkw+';pid='+pid204546+';place='+(plc204546++)+';rnd='+rnd+';click=CLICK_MACRO_PLACEHOLDER';

document.write('<scr'+'ipt src="'+absrc+'" type="text/javascript"></scr'+'ipt>');

</script>

      <div id="definition">
        <img alt="Package" src="../../../lib/package_big.png" />
        <p id="owner"><a href="../../package.html" class="extype" name="org">org</a>.<a href="../package.html" class="extype" name="org.scalatest">scalatest</a></p>
        <h1>exceptions</h1><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      </div>

      <h4 id="signature" class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">package</span>
      </span>
      <span class="symbol">
        <span class="name">exceptions</span>
      </span>
      </h4>
      
          <div id="comment" class="fullcommenttop"></div>
        

      <div id="mbrsel">
        <div id="textfilter"><span class="pre"></span><span class="input"><input id="mbrsel-input" type="text" accesskey="/" /></span><span class="post"></span></div>
        
        
        <div id="visbl">
            <span class="filtertype">Visibility</span>
            <ol><li class="public in"><span>Public</span></li><li class="all out"><span>All</span></li></ol>
          </div>
      </div>

      <div id="template">
        <div id="allMembers">
        

        <div id="types" class="types members">
              <h3>Type Members</h3>
              <ol><li name="org.scalatest.exceptions.DiscardedEvaluationException" visbl="pub" data-isabs="false" fullComment="yes" group="Ungrouped">
      <a id="DiscardedEvaluationExceptionextendsRuntimeException"></a>
      <a id="DiscardedEvaluationException:DiscardedEvaluationException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="DiscardedEvaluationException.html"><span class="name">DiscardedEvaluationException</span></a><span class="result"> extends <span class="extype" name="scala.RuntimeException">RuntimeException</span></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@DiscardedEvaluationExceptionextendsRuntimeException" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception that indicates an evaluation of a property should be discarded, because a condition
required by a property was not met by the passed values.</p><div class="fullcomment"><div class="comment cmt"><p>Exception that indicates an evaluation of a property should be discarded, because a condition
required by a property was not met by the passed values.</p><p>This exception is thrown by the <code>whenever</code> method defined in trait <a href="../prop/Whenever.html"><code>Whenever</code></a>
when the given condition is false. The <code>forAll</code> methods defined in trait <a href="../prop/PropertyChecks.html"><code>PropertyChecks</code></a>
catch the <code>DiscardedEvaluationException</code> and ignore it, moving on to try the next set of parameter values it is checking
th property against.
</p></div></div>
    </li><li name="org.scalatest.exceptions.DuplicateTestNameException" visbl="pub" data-isabs="false" fullComment="yes" group="Ungrouped">
      <a id="DuplicateTestNameExceptionextendsStackDepthException"></a>
      <a id="DuplicateTestNameException:DuplicateTestNameException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="DuplicateTestNameException.html"><span class="name">DuplicateTestNameException</span></a><span class="result"> extends <a href="StackDepthException.html" class="extype" name="org.scalatest.exceptions.StackDepthException">StackDepthException</a></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@DuplicateTestNameExceptionextendsStackDepthException" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception that indicates an attempt was made to register a test that had the same name as a test
already registered in the same suite.</p><div class="fullcomment"><div class="comment cmt"><p>Exception that indicates an attempt was made to register a test that had the same name as a test
already registered in the same suite. The purpose of this exception is to encapsulate information about
the stack depth at which the line of code that made this attempt resides, so that information can be presented to
the user that makes it quick to find the problem line of code. (In other words, the user need not scan through the
stack trace to find the correct filename and line number of the offending code.)
</p></div><dl class="attributes block"> <dt>Exceptions thrown</dt><dd><span class="cmt"><p><span class="extype" name="NullArgumentException"><code>NullArgumentException</code></span> if <code>testName</code> is <code>null</code></p></span></dd></dl></div>
    </li><li name="org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException" visbl="pub" data-isabs="false" fullComment="yes" group="Ungrouped">
      <a id="GeneratorDrivenPropertyCheckFailedExceptionextendsPropertyCheckFailedException"></a>
      <a id="GeneratorDrivenPropertyCheckFailedException:GeneratorDrivenPropertyCheckFailedException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="GeneratorDrivenPropertyCheckFailedException.html"><span class="name">GeneratorDrivenPropertyCheckFailedException</span></a><span class="result"> extends <a href="PropertyCheckFailedException.html" class="extype" name="org.scalatest.exceptions.PropertyCheckFailedException">PropertyCheckFailedException</a></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@GeneratorDrivenPropertyCheckFailedExceptionextendsPropertyCheckFailedException" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception that indicates a <a href="http://www.artima.com/shop/scalacheck">ScalaCheck</a> property check failed.</a></p><div class="fullcomment"><div class="comment cmt"><p>Exception that indicates a <a href="http://www.artima.com/shop/scalacheck">ScalaCheck</a> property check failed.
</p></div><dl class="attributes block"> <dt>Exceptions thrown</dt><dd><span class="cmt"><p><span class="extype" name="NullArgumentException"><code>NullArgumentException</code></span> if any parameter is <code>null</code> or <code>Some(null)</code>.</p></span></dd></dl></div>
    </li><li name="org.scalatest.exceptions.ModifiableMessage" visbl="pub" data-isabs="true" fullComment="yes" group="Ungrouped">
      <a id="ModifiableMessage[T&lt;:Throwable]extendsAnyRef"></a>
      <a id="ModifiableMessage[T&lt;:Throwable]:ModifiableMessage[T]"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">trait</span>
      </span>
      <span class="symbol">
        <a href="ModifiableMessage.html"><span class="name">ModifiableMessage</span></a><span class="tparams">[<span name="T">T &lt;: <span class="extype" name="scala.Throwable">Throwable</span></span>]</span><span class="result"> extends <span class="extype" name="scala.AnyRef">AnyRef</span></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@ModifiableMessage[T&lt;:Throwable]extendsAnyRef" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Trait implemented by exception types that can modify their detail message.</p><div class="fullcomment"><div class="comment cmt"><p>Trait implemented by exception types that can modify their detail message.</p><p>This trait facilitates the <code>withClue</code> construct provided by trait
<a href="../Assertions.html"><code>Assertions</code></a>. This construct enables extra information (or &quot;clues&quot;) to
be included in the detail message of a thrown exception. Although both
<code>assert</code> and <code>expect</code> provide a way for a clue to be
included directly, <code>assertThrows</code>, <code>intercept</code>, and ScalaTest matcher expressions
do not. Here's an example of clues provided directly in <code>assert</code>:</p><p><pre class="stHighlighted">
assert(<span class="stLiteral">1</span> + <span class="stLiteral">1</span> === <span class="stLiteral">3</span>, <span class="stQuotedString">"this is a clue"</span>)
</pre></p><p>and in <code>expect</code>:</p><p><pre class="stHighlighted">
expect(<span class="stLiteral">3</span>, <span class="stQuotedString">"this is a clue"</span>) { <span class="stLiteral">1</span> + <span class="stLiteral">1</span> }
</pre></p><p>The exceptions thrown by the previous two statements will include the clue
string, <code>"this is a clue"</code>, in the exceptions detail message.
To get the same clue in the detail message of an exception thrown
by a failed <code>assertThrows</code> call requires using <code>withClue</code>:</p><p><pre class="stHighlighted">
withClue(<span class="stQuotedString">"this is a clue"</span>) {
  assertThrows[<span class="stType">IndexOutOfBoundsException</span>] {
    <span class="stQuotedString">"hi"</span>.charAt(-<span class="stLiteral">1</span>)
  }
}
</pre></p><p>Similarly, to get a clue in the exception resulting from an exception arising out
of a ScalaTest matcher expression, you need to use <code>withClue</code>. Here's
an example:</p><p><pre class="stHighlighted">
withClue(<span class="stQuotedString">"this is a clue"</span>) {
  <span class="stLiteral">1</span> + <span class="stLiteral">1</span> should === (<span class="stLiteral">3</span>)
}
</pre></p><p>Exception types that mix in this trait have a <code>modifyMessage</code> method, which
returns an exception identical to itself, except with the detail message option replaced with
the result of invoking the passed function, supplying the current detail message option
as the lone <code>String</code> parameter.</p></div></div>
    </li><li name="org.scalatest.exceptions.ModifiablePayload" visbl="pub" data-isabs="true" fullComment="yes" group="Ungrouped">
      <a id="ModifiablePayload[T&lt;:Throwable]extendsAnyRef"></a>
      <a id="ModifiablePayload[T&lt;:Throwable]:ModifiablePayload[T]"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">trait</span>
      </span>
      <span class="symbol">
        <a href="ModifiablePayload.html"><span class="name">ModifiablePayload</span></a><span class="tparams">[<span name="T">T &lt;: <span class="extype" name="scala.Throwable">Throwable</span></span>]</span><span class="result"> extends <span class="extype" name="scala.AnyRef">AnyRef</span></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@ModifiablePayload[T&lt;:Throwable]extendsAnyRef" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Trait implemented by <a href="PayloadField.html"><code>PayloadField</code></a> exception types that can modify their payload.</a></p><div class="fullcomment"><div class="comment cmt"><p>Trait implemented by <a href="PayloadField.html"><code>PayloadField</code></a> exception types that can modify their payload.</p><p>This trait facilitates the <code>withPayload</code> construct provided by trait
<a href="../Payloads.html"><code>Payloads</code></a>. This construct enables a payload object (or modified
payload object) to be included as the payload of a thrown exception. The payload
can then be included in the ScalaTest event that results from that exception. For
example, the payload included in a <a href="TestFailedException.html"><code>TestFailedException</code></a> will be included
as the payload of the resulting <a href="../events/TestFailed.html"><code>TestFailed</code></a> event. Here's an example in
which a GUI snapshot is included as a payload when a test fails:</p><p><pre class="stHighlighted">
withPayload(generateGUISnapshot()) {
  <span class="stLiteral">1</span> + <span class="stLiteral">1</span> should === (<span class="stLiteral">3</span>)
}
</pre></p><p>Exception types that mix in this trait have a <code>modifyPayload</code> method, which
returns an exception identical to itself, except with the payload option replaced with
the result of invoking the passed function, supplying the current payload option
as the lone <code>Option[Any]</code> parameter.</p></div></div>
    </li><li name="org.scalatest.exceptions.NotAllowedException" visbl="pub" data-isabs="false" fullComment="yes" group="Ungrouped">
      <a id="NotAllowedExceptionextendsStackDepthException"></a>
      <a id="NotAllowedException:NotAllowedException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="NotAllowedException.html"><span class="name">NotAllowedException</span></a><span class="result"> extends <a href="StackDepthException.html" class="extype" name="org.scalatest.exceptions.StackDepthException">StackDepthException</a></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@NotAllowedExceptionextendsStackDepthException" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception that indicates something was attempted in test code that is not allowed.</p><div class="fullcomment"><div class="comment cmt"><p>Exception that indicates something was attempted in test code that is not allowed.
For example, in a <a href="../FeatureSpec.html"><code>FeatureSpec</code></a>, it is not allowed to nest a <code>feature</code>
clause inside another <code>feature</code> clause. If this is attempted, the construction
of that suite will fail with a <code>NotAllowedException</code>.
</p></div><dl class="attributes block"> <dt>Exceptions thrown</dt><dd><span class="cmt"><p><span class="extype" name="NullArgumentException"><code>NullArgumentException</code></span> if either <code>message</code> or <code>failedCodeStackDepthFun</code> is <code>null</code></p></span></dd></dl></div>
    </li><li name="org.scalatest.exceptions.PayloadField" visbl="pub" data-isabs="true" fullComment="yes" group="Ungrouped">
      <a id="PayloadFieldextendsAnyRef"></a>
      <a id="PayloadField:PayloadField"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">trait</span>
      </span>
      <span class="symbol">
        <a href="PayloadField.html"><span class="name">PayloadField</span></a><span class="result"> extends <span class="extype" name="scala.AnyRef">AnyRef</span></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@PayloadFieldextendsAnyRef" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Trait implemented by exception types that carry an optional payload.</p><div class="fullcomment"><div class="comment cmt"><p>Trait implemented by exception types that carry an optional payload.</p><p>Many ScalaTest events include an optional &quot;payload&quot; field that can be used
to pass information to a custom reporter. This trait facilitates such customization,
by allowing test code to include a payload in an exception (such as <code>TestFailedException</code>).
ScalaTest looks for this trait and fires any payloads it finds in the relevant ScalaTest event
stimulated by the exception, such as a <a href="../events/TestFailed.html"><code>TestFailed</code></a> event stimulated by a <code>TestFailedException</code>.
(Although in its initial
release there is only two subclasses of <code>PayloadField</code> in ScalaTest,
<a href="TestFailedException.html"><code>TestFailedException</code></a> and
<a href="TestCanceledException.html"><code>TestCanceledException</code></a>,
in future version of ScalaTest, there could be more)</p><p>For an example of how payloads could be used, see the documentation for trait <a href="../Payloads.html"><code>Payloads</code></a>.</p></div></div>
    </li><li name="org.scalatest.exceptions.PropertyCheckFailedException" visbl="pub" data-isabs="true" fullComment="yes" group="Ungrouped">
      <a id="PropertyCheckFailedExceptionextendsTestFailedException"></a>
      <a id="PropertyCheckFailedException:PropertyCheckFailedException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier">abstract </span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="PropertyCheckFailedException.html"><span class="name">PropertyCheckFailedException</span></a><span class="result"> extends <a href="TestFailedException.html" class="extype" name="org.scalatest.exceptions.TestFailedException">TestFailedException</a></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@PropertyCheckFailedExceptionextendsTestFailedException" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception that indicates a property check failed.</p><div class="fullcomment"><div class="comment cmt"><p>Exception that indicates a property check failed.
</p></div><dl class="attributes block"> <dt>Exceptions thrown</dt><dd><span class="cmt"><p><span class="extype" name="NullArgumentException"><code>NullArgumentException</code></span> if any parameter is <code>null</code> or <code>Some(null)</code>.</p></span></dd></dl></div>
    </li><li name="org.scalatest.exceptions.StackDepth" visbl="pub" data-isabs="true" fullComment="yes" group="Ungrouped">
      <a id="StackDepthextendsAnyRef"></a>
      <a id="StackDepth:StackDepth"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">trait</span>
      </span>
      <span class="symbol">
        <a href="StackDepth.html"><span class="name">StackDepth</span></a><span class="result"> extends <span class="extype" name="scala.AnyRef">AnyRef</span></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@StackDepthextendsAnyRef" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Trait that encapsulates the information required of an exception thrown by ScalaTest's assertions
and matchers, which includes a stack depth at which the failing line of test code resides.</p><div class="fullcomment"><div class="comment cmt"><p>Trait that encapsulates the information required of an exception thrown by ScalaTest's assertions
and matchers, which includes a stack depth at which the failing line of test code resides.</p><p>This trait exists so that it can be mixed into two exception superclasses, <a href="StackDepthException.html"><code>StackDepthException</code></a>,
from which extend several exceptions that do not depend on JUnit, and <a href="../junit/JUnitTestFailedError.html"><code>JUnitTestFailedError</code></a>, which
does depend on JUnit. The latter, which requires JUnit be in the classpath, ensures failed ScalaTest assertions are
reported as &quot;failures,&quot; not &quot;errors,&quot; by JUnit.</p></div></div>
    </li><li name="org.scalatest.exceptions.StackDepthException" visbl="pub" data-isabs="true" fullComment="yes" group="Ungrouped">
      <a id="StackDepthExceptionextendsRuntimeExceptionwithStackDepth"></a>
      <a id="StackDepthException:StackDepthException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier">abstract </span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="StackDepthException.html"><span class="name">StackDepthException</span></a><span class="result"> extends <span class="extype" name="scala.RuntimeException">RuntimeException</span> with <a href="StackDepth.html" class="extype" name="org.scalatest.exceptions.StackDepth">StackDepth</a></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@StackDepthExceptionextendsRuntimeExceptionwithStackDepth" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception class that encapsulates information about the stack depth at which the line of code that failed resides,
so that information can be presented to the user that makes it quick to find the failing line of code.</p><div class="fullcomment"><div class="comment cmt"><p>Exception class that encapsulates information about the stack depth at which the line of code that failed resides,
so that information can be presented to the user that makes it quick to find the failing line of code. (In other
words, the user need not scan through the stack trace to find the correct filename and line number of the problem code.)
Having a stack depth is more useful in a testing environment in which test failures are implemented as
thrown exceptions, as is the case in ScalaTest's built-in suite traits.
</p></div><dl class="attributes block"> <dt>Exceptions thrown</dt><dd><span class="cmt"><p><span class="extype" name="NullArgumentException"><code>NullArgumentException</code></span> if either <code>messageFun</code>, <code>cause</code> or <code>failedCodeStackDepthFun</code> is <code>null</code>, or <code>Some(null)</code>.</p></span></dd></dl></div>
    </li><li name="org.scalatest.exceptions.TableDrivenPropertyCheckFailedException" visbl="pub" data-isabs="false" fullComment="yes" group="Ungrouped">
      <a id="TableDrivenPropertyCheckFailedExceptionextendsPropertyCheckFailedException"></a>
      <a id="TableDrivenPropertyCheckFailedException:TableDrivenPropertyCheckFailedException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="TableDrivenPropertyCheckFailedException.html"><span class="name">TableDrivenPropertyCheckFailedException</span></a><span class="result"> extends <a href="PropertyCheckFailedException.html" class="extype" name="org.scalatest.exceptions.PropertyCheckFailedException">PropertyCheckFailedException</a></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@TableDrivenPropertyCheckFailedExceptionextendsPropertyCheckFailedException" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception that indicates a table-driven property check failed.</p><div class="fullcomment"><div class="comment cmt"><p>Exception that indicates a table-driven property check failed.</p><p>For an introduction to using tables, see the documentation for trait
<a href="../prop/TableDrivenPropertyChecks.html">TableDrivenPropertyChecks</a>.</p></div><dl class="attributes block"> <dt>Exceptions thrown</dt><dd><span class="cmt"><p><span class="extype" name="NullArgumentException"><code>NullArgumentException</code></span> if any parameter is <code>null</code> or <code>Some(null)</code>.</p></span></dd></dl></div>
    </li><li name="org.scalatest.exceptions.TestCanceledException" visbl="pub" data-isabs="false" fullComment="yes" group="Ungrouped">
      <a id="TestCanceledExceptionextendsStackDepthExceptionwithModifiableMessage[org.scalatest.exceptions.TestCanceledException]withPayloadFieldwithModifiablePayload[org.scalatest.exceptions.TestCanceledException]"></a>
      <a id="TestCanceledException:TestCanceledException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="TestCanceledException.html"><span class="name">TestCanceledException</span></a><span class="result"> extends <a href="StackDepthException.html" class="extype" name="org.scalatest.exceptions.StackDepthException">StackDepthException</a> with <a href="ModifiableMessage.html" class="extype" name="org.scalatest.exceptions.ModifiableMessage">ModifiableMessage</a>[<a href="TestCanceledException.html" class="extype" name="org.scalatest.exceptions.TestCanceledException">TestCanceledException</a>] with <a href="PayloadField.html" class="extype" name="org.scalatest.exceptions.PayloadField">PayloadField</a> with <a href="ModifiablePayload.html" class="extype" name="org.scalatest.exceptions.ModifiablePayload">ModifiablePayload</a>[<a href="TestCanceledException.html" class="extype" name="org.scalatest.exceptions.TestCanceledException">TestCanceledException</a>]</span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@TestCanceledExceptionextendsStackDepthExceptionwithModifiableMessage[org.scalatest.exceptions.TestCanceledException]withPayloadFieldwithModifiablePayload[org.scalatest.exceptions.TestCanceledException]" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception thrown to indicate a test has been canceled.</p><div class="fullcomment"><div class="comment cmt"><p>Exception thrown to indicate a test has been canceled.</p><p>A <em>canceled test</em> is one that is unable to run because a needed dependency, such as
an external database, is missing.</p><p>Canceled tests are ones that complete abruptly with a <code>TestCanceledException</code> after
starting.</p></div></div>
    </li><li name="org.scalatest.exceptions.TestFailedDueToTimeoutException" visbl="pub" data-isabs="false" fullComment="yes" group="Ungrouped">
      <a id="TestFailedDueToTimeoutExceptionextendsTestFailedExceptionwithTimeoutField"></a>
      <a id="TestFailedDueToTimeoutException:TestFailedDueToTimeoutException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="TestFailedDueToTimeoutException.html"><span class="name">TestFailedDueToTimeoutException</span></a><span class="result"> extends <a href="TestFailedException.html" class="extype" name="org.scalatest.exceptions.TestFailedException">TestFailedException</a> with <a href="TimeoutField.html" class="extype" name="org.scalatest.exceptions.TimeoutField">TimeoutField</a></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@TestFailedDueToTimeoutExceptionextendsTestFailedExceptionwithTimeoutField" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Subclass of <a href="TestFailedException.html"><code>TestFailedException</code></a> representing tests that failed because of a timeout.</a></p><div class="fullcomment"><div class="comment cmt"><p>Subclass of <a href="TestFailedException.html"><code>TestFailedException</code></a> representing tests that failed because of a timeout.</p><p>This exception is thrown by the <code>failAfter</code>
method of trait <a href="../concurrent/Timeouts.html"><code>Timeouts</code></a>, the <code>eventually</code> method of trait
<a href="../concurrent/Eventually.html"><code>Eventually</code></a>, and the <code>await</code> methods of trait
<a href="../concurrent/AsyncAssertions.html"><code>AsyncAssertions</code></a>.</p></div><dl class="attributes block"> <dt>Exceptions thrown</dt><dd><span class="cmt"><p><span class="extype" name="NullArgumentException"><code>NullArgumentException</code></span> if either <code>messageFun</code>, <code>cause</code> or <code>failedCodeStackDepthFun</code> is <code>null</code>, or <code>Some(null)</code>.</p></span></dd></dl></div>
    </li><li name="org.scalatest.exceptions.TestFailedException" visbl="pub" data-isabs="false" fullComment="yes" group="Ungrouped">
      <a id="TestFailedExceptionextendsStackDepthExceptionwithModifiableMessage[org.scalatest.exceptions.TestFailedException]withPayloadFieldwithModifiablePayload[org.scalatest.exceptions.TestFailedException]"></a>
      <a id="TestFailedException:TestFailedException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="TestFailedException.html"><span class="name">TestFailedException</span></a><span class="result"> extends <a href="StackDepthException.html" class="extype" name="org.scalatest.exceptions.StackDepthException">StackDepthException</a> with <a href="ModifiableMessage.html" class="extype" name="org.scalatest.exceptions.ModifiableMessage">ModifiableMessage</a>[<a href="TestFailedException.html" class="extype" name="org.scalatest.exceptions.TestFailedException">TestFailedException</a>] with <a href="PayloadField.html" class="extype" name="org.scalatest.exceptions.PayloadField">PayloadField</a> with <a href="ModifiablePayload.html" class="extype" name="org.scalatest.exceptions.ModifiablePayload">ModifiablePayload</a>[<a href="TestFailedException.html" class="extype" name="org.scalatest.exceptions.TestFailedException">TestFailedException</a>]</span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@TestFailedExceptionextendsStackDepthExceptionwithModifiableMessage[org.scalatest.exceptions.TestFailedException]withPayloadFieldwithModifiablePayload[org.scalatest.exceptions.TestFailedException]" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception that indicates a test failed.</p><div class="fullcomment"><div class="comment cmt"><p>Exception that indicates a test failed.</p><p>One purpose of this exception is to encapsulate information about
the stack depth at which the line of test code that failed resides, so that information can be presented to
the user that makes it quick to find the failing line of test code. (In other words, the user need not scan through the
stack trace to find the correct filename and line number of the failing test.)</p><p>Another purpose of this exception is to encapsulate a payload, an object to be included in a <a href="../events/TestFailed.html"><code>TestFailed</code></a> event
as its payload, so it can be consumed by a custom reporter that understands the payload. For example, tests could take a screen
shot image of a GUI when a test fails, and include that as a payload. A custom reporter could listen for such payloads and
display the screen shots to the user.</p></div><dl class="attributes block"> <dt>Exceptions thrown</dt><dd><span class="cmt"><p><span class="extype" name="NullArgumentException"><code>NullArgumentException</code></span> if either <code>messageFun</code>, <code>cause</code> or <code>failedCodeStackDepthFun</code> is <code>null</code>, or <code>Some(null)</code>.</p></span></dd></dl></div>
    </li><li name="org.scalatest.exceptions.TestPendingException" visbl="pub" data-isabs="false" fullComment="yes" group="Ungrouped">
      <a id="TestPendingExceptionextendsRuntimeException"></a>
      <a id="TestPendingException:TestPendingException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="TestPendingException.html"><span class="name">TestPendingException</span></a><span class="result"> extends <span class="extype" name="scala.RuntimeException">RuntimeException</span></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@TestPendingExceptionextendsRuntimeException" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception thrown to indicate a test is pending.</p><div class="fullcomment"><div class="comment cmt"><p>Exception thrown to indicate a test is pending.</p><p>A <em>pending test</em> is one that has been given a name but is not yet implemented. The purpose of
pending tests is to facilitate a style of testing in which documentation of behavior is sketched
out before tests are written to verify that behavior (and often, the before the behavior of
the system being tested is itself implemented). Such sketches form a kind of specification of
what tests and functionality to implement later.</p><p>To support this style of testing, a test can be given a name that specifies one
bit of behavior required by the system being tested. The test can also include some code that
sends more information about the behavior to the reporter when the tests run. At the end of the test,
it can call method <code>pending</code>, which will cause it to complete abruptly with <code>TestPendingException</code>.
Because tests in ScalaTest can be designated as pending with <code>TestPendingException</code>, both the test name and any information
sent to the reporter when running the test can appear in the report of a test run. (In other words,
the code of a pending test is executed just like any other test.) However, because the test completes abruptly
with <code>TestPendingException</code>, the test will be reported as pending, to indicate
the actual test, and possibly the functionality, has not yet been implemented.</p></div></div>
    </li><li name="org.scalatest.exceptions.TestRegistrationClosedException" visbl="pub" data-isabs="false" fullComment="yes" group="Ungrouped">
      <a id="TestRegistrationClosedExceptionextendsStackDepthException"></a>
      <a id="TestRegistrationClosedException:TestRegistrationClosedException"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">class</span>
      </span>
      <span class="symbol">
        <a href="TestRegistrationClosedException.html"><span class="name">TestRegistrationClosedException</span></a><span class="result"> extends <a href="StackDepthException.html" class="extype" name="org.scalatest.exceptions.StackDepthException">StackDepthException</a></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@TestRegistrationClosedExceptionextendsStackDepthException" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Exception that indicates an action that is only allowed during a suite's test registration phase,
such as registering a test to run or ignore, was attempted after registration had already closed.</p><div class="fullcomment"><div class="comment cmt"><p>Exception that indicates an action that is only allowed during a suite's test registration phase,
such as registering a test to run or ignore, was attempted after registration had already closed.</p><p>In suites that register tests as functions, such as <a href="../FunSuite.html"><code>FunSuite</code></a> and <a href="../FunSpec.html"><code>FunSpec</code></a>, tests
are normally registered during construction. Although it is not the usual approach, tests can also
be registered after construction by invoking methods that register tests on the already constructed suite so
long as <code>run</code> has not been invoked on that suite.
As soon as <code>run</code> is invoked for the first time, registration of tests is &quot;closed,&quot; meaning
that any further attempts to register a test will fail (and result in an instance of this exception class being thrown). This
can happen, for example, if an attempt is made to nest tests, such as in a <code>FunSuite</code>:</p><p><pre class="stHighlighted">
test(<span class="stQuotedString">"this test is fine"</span>) {
  test(<span class="stQuotedString">"but this nested test is not allowed"</span>) {
  }
}
</pre></p><p>This exception encapsulates information about the stack depth at which the line of code that made this attempt resides,
so that information can be presented to the user that makes it quick to find the problem line of code. (In other words,
the user need not scan through the stack trace to find the correct filename and line number of the offending code.)</p></div><dl class="attributes block"> <dt>Exceptions thrown</dt><dd><span class="cmt"><p><span class="extype" name="NullArgumentException"><code>NullArgumentException</code></span> if either <code>message</code> or <code>failedCodeStackDepthFun</code> is <code>null</code></p></span></dd></dl></div>
    </li><li name="org.scalatest.exceptions.TimeoutField" visbl="pub" data-isabs="true" fullComment="yes" group="Ungrouped">
      <a id="TimeoutFieldextendsAnyRef"></a>
      <a id="TimeoutField:TimeoutField"></a>
      <h4 class="signature">
      <span class="modifier_kind">
        <span class="modifier"></span>
        <span class="kind">trait</span>
      </span>
      <span class="symbol">
        <a href="TimeoutField.html"><span class="name">TimeoutField</span></a><span class="result"> extends <span class="extype" name="scala.AnyRef">AnyRef</span></span>
      </span>
      </h4><span class="permalink">
      <a href="../../../index.html#org.scalatest.exceptions.package@TimeoutFieldextendsAnyRef" title="Permalink" target="_top">
        <img src="../../../lib/permalink.png" alt="Permalink" />
      </a>
    </span>
      <p class="shortcomment cmt">Trait mixed into exceptions thrown due to a timeout, which offers
a <code>timeout</code> field providing a <a href="../time/Span.html"><code>Span</code></a> representing the timeout that expired.</a></code></p><div class="fullcomment"><div class="comment cmt"><p>Trait mixed into exceptions thrown due to a timeout, which offers
a <code>timeout</code> field providing a <a href="../time/Span.html"><code>Span</code></a> representing the timeout that expired.</p><p>This trait is used by trait <a href="../concurrent/TimeLimitedTests.html"><code>TimeLimitedTests</code></a> to detect exceptions thrown because of timeouts, and
for such exceptions, to modify the message to more clearly indicate a test timed out. (Although in its initial
release there is only one subclass of <code>TimeoutField</code> in ScalaTest,
<a href="TestFailedDueToTimeoutException.html"><code>TestFailedDueToTimeoutException</code></a>,
in future version of ScalaTest, there could be more)</p></div></div>
    </li></ol>
            </div>

        

        

        

        
        </div>

        <div id="inheritedMembers">
        
        
        </div>

        <div id="groupedMembers">
        <div class="group" name="Ungrouped">
              <h3>Ungrouped</h3>
              
            </div>
        </div>

      </div>

      <div id="tooltip"></div>

      <div id="footer">  </div>


    </body>
      </html>
